export const musicGenres: string[] = [
	"Barroco",
	"Clássico",
	"Pop",
	"Rock",
	"Jazz",
	"Blues",
	"R&B (Rhythm and Blues)",
	"House",
	"Techno",
	"Trance",
	"Fado (Portugal)",
	"Flamenco (Espanha)",
	"Afrobeat",
	"Reggaeton",
	"Indie Rock",
	"Indie Pop",
	"Gospel",
	"Música Cristã Contemporânea",
	"Trilhas Sonoras",
	"Música de Filmes de Ação",
	"Música New Age",
	"Música Infantil",
	"Música Instrumental",
];

export const musicExamples: { genre: string; example: string }[] = [
	{
		genre: "Barroco",
		example: "Brandenburg Concerto No. 3 - Johann Sebastian Bach",
	},
	{ genre: "Clássico", example: "Symphony No. 5 - Ludwig van Beethoven" },
	{ genre: "Pop", example: "Billie Jean - Michael Jackson" },
	{ genre: "Rock", example: "Stairway to Heaven - Led Zeppelin" },
	{ genre: "Jazz", example: "Take Five - Dave Brubeck" },
	{ genre: "Blues", example: "The Thrill is Gone - B.B. King" },
	{ genre: "R&B (Rhythm and Blues)", example: "Respect - Aretha Franklin" },
	{ genre: "House", example: "One More Time - Daft Punk" },
	{ genre: "Techno", example: "Strings of Life - Derrick May" },
	{ genre: "Trance", example: "Adagio for Strings - Tiësto" },
	{
		genre: "Fado (Portugal)",
		example: "Uma Casa Portuguesa - Amália Rodrigues",
	},
	{ genre: "Flamenco (Espanha)", example: "Entre Dos Aguas - Paco de Lucía" },
	{ genre: "Afrobeat", example: "Water No Get Enemy - Fela Kuti" },
	{ genre: "Reggaeton", example: "Gasolina - Daddy Yankee" },
	{ genre: "Indie Rock", example: "Mr. Brightside - The Killers" },
	{ genre: "Indie Pop", example: "Electric Feel - MGMT" },
	{ genre: "Gospel", example: "Oh Happy Day - Edwin Hawkins Singers" },
	{
		genre: "Música Cristã Contemporânea",
		example: "Oceans (Where Feet May Fail) - Hillsong United",
	},
	{
		genre: "Trilhas Sonoras",
		example: "The Imperial March - John Williams (Star Wars)",
	},
	{
		genre: "Música de Filmes de Ação",
		example: "Eye of the Tiger - Survivor (Rocky III)",
	},
	{ genre: "Música New Age", example: "Return to Innocence - Enigma" },
	{ genre: "Música Infantil", example: "Baby Shark - Pinkfong" },
	{ genre: "Música Instrumental", example: "Clair de Lune - Claude Debussy" },
];
